uploads = []
generated = []

[[outputs]]
id = "d2Dpph4f-ls1sjd-65QDT"
uri = "file://Nestwork_Android_Veiledning.md"
type = "text"
title = "Android-veiledning (Chrome + Samsung Internet)"

[[outputs]]
id = "aZo2Iufl_MIQdwSTYm_Ha"
uri = "file://nestwork-vaktapp.tar.gz"
type = "unspecified"
title = "Nestwork Vaktapp - Prosjektfiler"

[[outputs]]
id = "fOSYGj__YLAsppWyqzhms"
uri = "file://nestwork-keystore.tar.gz"
type = "unspecified"
title = "nestwork-keystore.tar.gz"
